package rensim;

/**
 * Collision event generated by the Java-side starter collision solver.
 *
 * @param bodyA first body id
 * @param bodyB second body id
 * @param normal unit normal pointing from body A toward body B
 * @param penetrationMeters overlap depth in meters
 * @param relativeNormalVelocityMps normal relative speed before impulse in meters per second
 * @param impulseNewtonSeconds applied impulse magnitude in N*s
 */
public record CollisionContact(
    int bodyA,
    int bodyB,
    Vec3 normal,
    double penetrationMeters,
    double relativeNormalVelocityMps,
    double impulseNewtonSeconds) {}